apiVersion: apps/v1
kind: Deployment
metadata:
  name: simpleapi-k8-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simpleapi-k8
  template:
    metadata:
      labels:
        app: simpleapi-k8
    spec:
      containers:
      - name: simpleapi-k8
        image: simpleapi-k8:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080